corner-radius = 15.0;

rounded-corners-exclude = [
    "class_g = 'notpolybar'"
];

shadow = true;
shadow-radius = 15;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.85;
shadow-exclude = [ "name = 'Notification'", "class_g = 'notpolybar'", "class_g = 'Conky'", "class_g ?= 'Notify-osd'", "class_g = 'Cairo-clock'" ];
menu-opacity = 0.8;
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 0.0;

backend = "glx";

# Blur Settings
blur: {
    method = "dual_kawase";
    strength = 10;
    background = false;
    background-frame = false;
    background-fixed = false;
}

blur-background-exclude = [
  "name = 'Polybar'",
  "window_type = 'dock'",
    "window_type = 'desktop'",
      "_GTK_FRAME_EXTENTS@:c"
      ];

# Vsync not working
#vsync = true;
